#!/usr/bin/perl

$n = scalar @ARGV;
print "this is $n\n";

if(scalar @ARGV<1){
	print	"Usage:\n";
	print	"    ctags_gen *.v\n";
	exit 0;
}
open(OFILE,">tags") || print "Warning:can not open file:tags\n";

printf OFILE '!_TAG_FILE_FORMAT	2	/extended format; --format=1 will not append ;" to lines/' . "\n";
printf OFILE '!_TAG_FILE_SORTED	1	/0=unsorted, 1=sorted, 2=foldcase/' . "\n";
printf OFILE '!_TAG_PROGRAM_AUTHOR	Darren Hiebert	/dhiebert@users.sourceforge.net/' . "\n";
printf OFILE '!_TAG_PROGRAM_NAME	Exuberant Ctags	//' . "\n";
printf OFILE '!_TAG_PROGRAM_URL	http://ctags.sourceforge.net	/official site/' . "\n";
printf OFILE '!_TAG_PROGRAM_VERSION	5.5.4	//' . "\n";

while(scalar @ARGV >= 1){
	$file = shift @ARGV;
	open(IFILE,$file) || print "Warning:can not open file:$file\n";
	while($line = <IFILE>){
		chomp($line);
		if($line =~ /^\s*module\s+\w/){
			$inst = $line;
			$inst =~ s/^\s*module\s+(\w+).*$/$1/;
			$line =~ s/\//\\\//g;
			#search with '/what/', so will escape char '/' with '\/' in what
			if (exists $hash_array{$inst}){
				printf "Warning: file $file - module $inst, Had be defined before!\n";
				last
			}
			printf "Info: file $file - module $inst\n";
			$hash_array{$inst} = "\t".$file."\t".'/^'.$line.'$/;"'."\tm\n";
			break
		}
	}
	close(IFILE);
}
foreach $key (sort keys %hash_array){
	printf OFILE $key . $hash_array{$key};
}
close(OFILE);

exit 0;
